name: Security CI (Reusable)

on:
  workflow_call:
    inputs:
      service_name:
        required: false
        type: string
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo that actually contains the actions (Repo A = DEV)
      - name: Checkout DEV (actions repo)
        uses: actions/checkout@v4
        with:
          repository: saicharank0513-sys/DEV
          ref: main            # or a tag like v1 once you create it
          path: dev-src        # <â€” will create ./dev-src

      # 2) Now call the local actions from that checked-out folder
      - name: Run SAST
        uses: ./dev-src/.github/actions/sast

      - name: Run SonarQube Coverage
        uses: ./dev-src/.github/actions/sonarqube

      - name: Run Unit Tests
        uses: ./dev-src/.github/actions/unittest

      - name: Orchestrator message
        if: ${{ inputs.service_name != '' }}
        shell: bash
        run: echo "microservice-updated-${{ inputs.service_name }}"
